spring:
  rabbitmq:
    host: 192.168.126.19
    port: 5672
    username: test
    password: 123456
  zipkin:
    base-url: http://192.168.126.19:9411
  sleuth:
    sampler:
      probability: 1
logging:
  level:
    org.springframework.cloud.openfeign: debug
server:
  port: 9000
zuul:
  ignored-services: "*"
  sensitive-headers:
  routes:
    product:
      path: /productSys/**
      serviceId: product
    user: 
      path: /userSys/**
      serviceId: user
    order:
      path: /orderSys/**
      serviceId: order
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
auth:
  allowedAllURIs: /userSys/login/.*
  allowedBuyerURIs: /orderSys/order/create
  allowedSellerURIs: /orderSys/order/finish

