spring:
  rabbitmq:
    host: 192.168.126.19
    port: 5672
    username: test
    password: 123456
server:
  port: 9000
zuul:
  ignored-services: *
  sensitive-headers:
  routes:
    product:
      path: /productSys/**
      serviceId: product
    user: 
      path: /userSys/**
      serviceId: user
    order:
      path: /orderSys/**
      serviceId: order
auth:
  allowedAllURIs: /userSys/login/.*
  allowedBuyerURIs: /orderSys/order/create
  allowedSellerURIs: /orderSys/order/finish

